# Generated by Django 3.2.15 on 2022-12-08 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_cartitemmodel_cartmodel_ordermodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartmodel',
            name='cart',
        ),
        migrations.AddField(
            model_name='cartitemmodel',
            name='cart',
            field=models.ManyToManyField(to='shop.CartModel'),
        ),
    ]
