# Generated by Django 3.2.15 on 2022-12-10 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20221208_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitemmodel',
            name='total_price',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='total_price', to='shop.productmodel'),
        ),
        migrations.AlterField(
            model_name='cartitemmodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='shop.productmodel'),
        ),
    ]
