# Generated by Django 3.2.15 on 2022-12-10 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20221210_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitemmodel',
            name='total_price',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='total_price', to='shop.productmodel'),
        ),
    ]
