# Generated by Django 3.2.15 on 2022-12-10 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_cartitemmodel_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitemmodel',
            name='total_price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='total_price', to='shop.productmodel'),
        ),
    ]
