# Generated by Django 3.2.15 on 2022-12-10 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_cartitemmodel_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitemmodel',
            name='total_price',
        ),
    ]
