# Generated by Django 3.2.15 on 2022-12-10 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_remove_cartitemmodel_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='cart',
            field=models.ManyToManyField(to='shop.CartModel'),
        ),
    ]
