# Generated by Django 3.2.15 on 2022-12-11 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_ordermodel_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartmodel',
            name='ordered',
        ),
    ]
