# Generated by Django 3.2.15 on 2022-12-11 12:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_remove_cartmodel_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='shop.productmodel'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='cart',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='cart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='shop.cartmodel'),
            preserve_default=False,
        ),
    ]
