# Generated by Django 3.2.15 on 2022-12-11 12:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20221211_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 11, 13, 40, 41, 566080)),
        ),
    ]
