# Generated by Django 3.2.15 on 2022-12-11 13:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_ordermodel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartmodel',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 11, 14, 36, 0, 671512)),
        ),
    ]
